- name: 執行抓取
        run: python chuck/2.exchange.py
      - name: 提交並推送更新
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add chuck/rates.json
          git commit -m "Update rates" || exit 0
          git push