name: Update Finance Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance requests
      - run: python 2.exchange.py
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add history.json rates.json
          git commit -m "update data" || exit 0
          git push origin main